/*
 * Code generated from Atmel Start.
 *
 * This file will be overwritten when reconfiguring your Atmel Start project.
 * Please copy examples or other code you want to keep to a separate file
 * to avoid losing it when reconfiguring.
 */
#ifndef ATMEL_START_PINS_H_INCLUDED
#define ATMEL_START_PINS_H_INCLUDED

#include <hal_gpio.h>

// SAMD51 has 14 pin functions

#define GPIO_PIN_FUNCTION_A 0
#define GPIO_PIN_FUNCTION_B 1
#define GPIO_PIN_FUNCTION_C 2
#define GPIO_PIN_FUNCTION_D 3
#define GPIO_PIN_FUNCTION_E 4
#define GPIO_PIN_FUNCTION_F 5
#define GPIO_PIN_FUNCTION_G 6
#define GPIO_PIN_FUNCTION_H 7
#define GPIO_PIN_FUNCTION_I 8
#define GPIO_PIN_FUNCTION_J 9
#define GPIO_PIN_FUNCTION_K 10
#define GPIO_PIN_FUNCTION_L 11
#define GPIO_PIN_FUNCTION_M 12
#define GPIO_PIN_FUNCTION_N 13

#define ADC_PLUS GPIO(GPIO_PORTA, 2)
#define ADC_MINUS GPIO(GPIO_PORTA, 3)
#define HALL_C GPIO(GPIO_PORTA, 4)
#define HALL_B GPIO(GPIO_PORTA, 5)
#define HALL_A GPIO(GPIO_PORTA, 6)
#define HALL_OUT GPIO(GPIO_PORTA, 7)
#define ECAT_SPI_DATA0 GPIO(GPIO_PORTA, 8)
#define ECAT_SPI_DATA1 GPIO(GPIO_PORTA, 9)
#define ECAT_SPI_DATA2 GPIO(GPIO_PORTA, 10)
#define ECAT_SPI_DATA3 GPIO(GPIO_PORTA, 11)
#define ECAT_GPIO1 GPIO(GPIO_PORTA, 12)
#define ECAT_GPIO2 GPIO(GPIO_PORTA, 13)
#define ECAT_GPIO3 GPIO(GPIO_PORTA, 14)
#define ECAT_GPIO4 GPIO(GPIO_PORTA, 15)
#define PWM_C GPIO(GPIO_PORTA, 16)
#define PWM_B GPIO(GPIO_PORTA, 17)
#define PWM_A GPIO(GPIO_PORTA, 18)
#define EN_C GPIO(GPIO_PORTA, 19)
#define EN_B GPIO(GPIO_PORTA, 20)
#define EN_A GPIO(GPIO_PORTA, 21)
#define NSLEEP GPIO(GPIO_PORTA, 22)
#define NFAULT GPIO(GPIO_PORTA, 23)
#define ENCODER_SPI_MISO GPIO(GPIO_PORTA, 24)
#define ENCODER_SPI_MOSI GPIO(GPIO_PORTA, 25)
#define STATUS_LED1 GPIO(GPIO_PORTA, 27)
#define ENCODER_SPI_NCS GPIO(GPIO_PORTB, 2)
#define ENCODER_SPI_SCK GPIO(GPIO_PORTB, 3)
#define ADC_A GPIO(GPIO_PORTB, 8)
#define ADC_B GPIO(GPIO_PORTB, 9)
#define ECAT_SPI_SCK GPIO(GPIO_PORTB, 10)
#define ECAT_SPI_CS GPIO(GPIO_PORTB, 11)
#define STATUS_LED2 GPIO(GPIO_PORTB, 23)

#endif // ATMEL_START_PINS_H_INCLUDED
